### ISSUE TITLE
coinslot status

### ISSUE THREAD

**Issue by pseudongMabata** [ivanalayan15/JuanFi#102]
am indicator that will be displayed in thescreen/ indicated by light if the coinslot is full for instace:

puno na yung caha nya sa loob then yung mga coin naiimbak na sa bunganga ng coinslot tas mag faflash sa screen na coinslot not available

niluluwa naman niya yung coin pag full na yung box pero minsan na mimisunderstood ng client na didaw tinatanggap coins nila yun pala puno na si coinslot 

another request - whenever the user click cancel the indicator light or the screen will return to default display (when there is no coins inserted) just like the connect button that will immediately turn off the indicator if the user already funished entering coins. to prevent confusion to the next user of the vendo/ coinslot.

**Comment by rexsllemel** [comment]
> another request - whenever the user click cancel the indicator light or the screen will return to default display (when there is no coins inserted) just like the connect button that will immediately turn off the indicator if the user already funished entering coins. to prevent confusion to the next user of the vendo/ coinslot.

this was already fixed using latest version.
