### ISSUE TITLE
Theme Contribution

### ISSUE THREAD

**Issue by smrtrnx** [ivanalayan15/JuanFi#113]
Hello Sir Ivan(@ivanalayan15 ),

I have something to share with regards to the portal template. I have it on my repository called [JuanFiTemplate](https://github.com/smrtrnx/JuanFiTemplate). 

It's my way of saying thank you. I hope this won't  make you disappointed :)

Kind Regards,

**Comment by ivanalayan15** [comment]
@smrtrnx wow this is nice let me test thsi one
