### ISSUE TITLE
Buzzer Pin 

### ISSUE THREAD

**Issue by cyberprime008** [ivanalayan15/JuanFi#115]
pwede po bang my Buzzer pin

**Comment by mrr3gx** [comment]
Yes ito sana ung irerequest ko. sana merong buzzer pin. like kung twing may maghuhulog magbabuzz.

**Comment by ivanalayan15** [comment]
merong gnung coinslot n nabbili

**Comment by iokdss** [comment]
Baka ang ibig nyang sabihin sir na buzzer hindi sa coinslot counter, Yung mag beep ang vendo sa countdown ng coinslot insert wait time countdown. Mag beep every seconds po. Pag press ng done mag generae ng code. Then mag start ulit yung countdown pero di na mag beep mag beep ulit pag 10 seconds nlng natira sa countdown mag beep sya ulit hanggang matapos ang 10 seconds to aware the client na dapat mag take na sya ng photo sa generated code sa LCD or to screenshot na code before mawala po. Parang countdown ng timebomb po. ;)

**Comment by ivanalayan15** [comment]
Already implemented
