### ISSUE TITLE
Push button reset RST & G client problem

### ISSUE THREAD

**Issue by rgohms** [ivanalayan15/JuanFi#120]
Hi sir May paraan po kaya hnd na kaylangan gamitin Yong push button tuwing gagamit ng insert coins..hnd kasi alam ng client gamitin.. Kaya langing may bantay Yong vendo,parang naka voucher type parin.hnd pwedeng Iwan, kaylangan may magtuturo. Salamat

**Comment by rgohms** [comment]
May paraan po kaya hnd na kaylangan gamitin Yong push button tuwing gagamit ng insert coins.. Nahihirapan Yong client pumasok sa Insert coins pag hnd ma push

**Comment by rgohms** [comment]
May paraan po kaya hnd na kaylangan gamitin Yong push button tuwing gagamit ng insert coins.. Nahihirapan Yong client pumasok sa Insert coins pag hnd ma push

**Comment by ivanalayan15** [comment]
setup issue mo yn d naman tlga kaylangan irestart yn eh inde stable ang connection ng system mo pag gnyn

**Comment by rgohms** [comment]
> setup issue mo yn d naman tlga kaylangan irestart yn eh inde stable ang connection ng system mo pag gnyn

cge ..thank you sir
