### ISSUE TITLE
Edit of NodeMCU Voucher Profice via API thru Mikrotik Terminal

### ISSUE THREAD

**Issue by ElvinSDagohoy** [ivanalayan15/JuanFi#126]
Dear Sir Ivan,

I am using multi vendo by assigning each sub-vendo with a different Voucher Profile and Code Prefix. There are instances that I pre-flash back up NodeMCU for contingency measures or reassign sub vendo to different stores. It will take so much time to open Nodemcu admin portal especially remote access thru Remote Winbox. It is easier , faster and more convenient if edit of NodeMCU Voucher Profile and Code Prefix can be done using API Script thru Mikrotik Terminal just like the convenience of changing the rates.

Respectfully yours,

Elvin Sotto Dagohoy
Davao City Philippines

**Comment by ivanalayan15** [comment]
Answered in the group already
