### ISSUE TITLE
JuanFI v3.3 portal problem / admin/ slow to redirect or connect/ no connection 

### ISSUE THREAD

**Issue by earlvincent16** [ivanalayan15/JuanFi#133]
Sir Ivan Ask lang ako how to fix slow to redirect portal and sometimes cannot redirect to portal and admin.
nung unang try ko past 2 months ago na since ginamit ko si v3.3 juanfi ok naman siya but this month nagiging abnormal ang portal and admin niya at minsan pag nag hulog ng coins nag like 5 pesos, dinadagdagan umabot na sa 100 pesos yung credit ni client kahit 5 pesos lang hinulog niya.. thank you 
#AP used EAP110 
#mikrotik haplite
#single vendo
#first trial ni juanfi

**Comment by ivanalayan15** [comment]
setup and configuration issue
