### ISSUE TITLE
Mini display for vendor.

### ISSUE THREAD

**Issue by ke8lne** [ivanalayan15/JuanFi#136]
Not really needed but could help some other vendors to monitor their machine by just looking at the display like showing the current sales, active users, ip and status.

One thing is the lcd display can be connected to different addresses for the i2c but the ssd1306 can't.
I'm doing this plan to my esp8366 wireless based machine using the source code but I don't have an esp32 modules that I could test for.
Thank you for reviewing this suggestion.

**Comment by ivanalayan15** [comment]
you can download juanfi manager for this one it has the things your looking for
