### ISSUE TITLE
No Mac Control Panel

### ISSUE THREAD

**Issue by owngravity** [ivanalayan15/JuanFi#138]
I can't connect my tapo CCTV to the Piso wifi. I would like to request a Mac Control panel to allow and block Mac addresses

**Comment by Kintoyyy** [comment]
## Just use the Bypassed option in the IP Bindings


![image](https://github.com/ivanalayan15/JuanFi/assets/56209108/d81eccca-7967-4a89-b098-1ba590642d47)

**Comment by ivanalayan15** [comment]
closing the issue
