### ISSUE TITLE
Invalid voucher after disconnected to wifi or after puase time

### ISSUE THREAD

**Issue by AvePisowifi** [ivanalayan15/JuanFi#139]
Ano po solution sa nawawala oras ni client after magpause kahit mahaba pa validity

**Comment by ivanalayan15** [comment]
this should be an issue on random mac address

**Comment by edmarlozada** [comment]
@AvePisowifi 
possible cause is the "admin console\system configuration\voucher login option\username only" at ang config.js "var loginOption = 0" ay hindi magka parehas. dapat pag "username only" onConfig.js should be "var loginOption = 0" at pag "username + password" onConfig.js should be "var loginOption = 1"
