### ISSUE TITLE
Issue on System Clock after upgrade to v4.3

### ISSUE THREAD

**Issue by mugnet** [ivanalayan15/JuanFi#155]
Hi sir thank you sa opensource platform, issue ko lang po lagi kapag nag-upgrade ng 4.2 to 4.3 nagiging Jan 1, 1970 yung system clock. Naupdate ko na lahat sa mikrotik even NTP client and clock settings related to it.
Thank you.

**Comment by MeeeMaaaaw** [comment]
Kindly disregard .. not a big deal issue. I think sa ROS na yata ang issue kasi before kahit 4.3 ang gamit ko tama naman ang time pero nung nagupdate yung ROS naeencounter ko na tong issue.

**Comment by MeeeMaaaaw** [comment]
BTW reflashing will fix the issue but mga ilang months lang babalik lang yan ulit sa ganyan kaya i-disregard mo nalang yang issue sa time.

**Comment by mugnet** [comment]
sa ROS nga boss, triny ko sa hexs v7 nagwork naman. Salamat sa sagot.
