### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by ivanalayan15** [ivanalayan15/JuanFi#17]
ESP32 support
-code to be compile in ESP32 for next gen lan implementation

**Comment by charmedonesfjo** [comment]
pwede makita ang .INO ng ESP32 try ko revised for WiFi enabled and PROGMEM HTML base

**Comment by ivanalayan15** [comment]
on it po nililinis ko po yung codes po since many library yung kailangan idownload to compile it

**Comment by ivanalayan15** [comment]
@charmedonesfjo meron akong finorked na library s telnet para mgcompatible ung esp32

https://github.com/ivanalayan15/ESP-Telnet-Client
