### ISSUE TITLE
Juanfi Setup takes too long or never detected

### ISSUE THREAD

**Issue by smrtrnx** [ivanalayan15/JuanFi#24]
Hi Ivan,

I am trying to use the .ino file other than the binary release files. I have noticed that when flashing .ino setup doesn't seem to show up in my wifi network. Yet but with binary it works juat fine.

Any advice?

**Comment by ivanalayan15** [comment]
hello, did you upload the SIFSS image?

**Comment by smrtrnx** [comment]
do you mean the data files **JuanFi-master**\**JuanFi-nodemcu**\**data** yes using sketch data upload

**Comment by ivanalayan15** [comment]
yes, hmmm that is weird,is there any can you show me the screenshot for Serial Log

**Comment by smrtrnx** [comment]
i'll try to provide one. anyway thank you for this wonderful opensource project of yours. keeps me busy on this pandemic :)

**Comment by ivanalayan15** [comment]
thank you, this make me also always at home instead of going outside to hangout :-)

**Comment by smrtrnx** [comment]
same here Ivan, cheers! lets get this project going

**Comment by ivanalayan15** [comment]
@smrtrnx  i think i already know the issue, because the one in the .ino file is 45 seconds... and in the bin file still old which is 15 second only, it should show after 45 seconds

**Comment by smrtrnx** [comment]
hmmm let me test that out changing it to 15000 on .ino

**Comment by smrtrnx** [comment]
Fantastic! it works just fine right now. Thank you Ivan I've set it to 8 seconds :)

**Comment by ivanalayan15** [comment]
nice hehe. i will close this ticket then

**Comment by thekailanihouse** [comment]
hi @ivanalayan15 , can i use this repo for WEMOS D1 R2?

what im done:

1. using all library what this repo needs
2. uploading /data/admin folder to data sketch

but im getting error like this
![image](https://user-images.githubusercontent.com/76886095/154832316-97069bd3-8775-4f4c-a434-2331c5bea70f.png)
