### ISSUE TITLE
Assigning Static IP on esp8266

### ISSUE THREAD

**Issue by smrtrnx** [ivanalayan15/JuanFi#25]
Hi maybe this helps lets try to assign a static ip address on the device. using the esp8266WiFi.h library. i think this stops mikrotik from assigning a dynamic ip address each time esp8266 disconnected from the server.

//Define Static IP Settings
IPAddress local_IP(192,168,5,253);
IPAddress gateway(192,168,5,1);
IPAddress subnet(255,255,255,0);
IPAddress primaryDNS(8,8,8,8);
IPAddress secondaryDNS(8,8,4,4);

**Comment by ivanalayan15** [comment]
hello, currently the solution i have on this issue is not on the JuanFi setup its rather we do it on MT config, we can set a static ip for a specific mac address

**Comment by smrtrnx** [comment]
yup, i've been testing the whole time using the same method but every time you unplugged  the vendo for some reason and the dhcp leases expires. it will get you back on the initial setup. on the other hand when it tries to connect it does not uses the assign static ip anymore but rather the dhcp serves lease issue another ip address on the device. :)

**Comment by ivanalayan15** [comment]
really... that is really weird many actually using this kind of method already and its working fine, my vendo itself running 5 mos already using the same ip and its not really changing at all. may be your mac address is being change?

**Comment by smrtrnx** [comment]
I am using laptop to for the initial setup. thus it does not generate randomized mac. have you tried unplugging your vendo like over night?

**Comment by ivanalayan15** [comment]
yes, i tried and also days actually

**Comment by smrtrnx** [comment]
I don't know what exactly happens here in my end tried both method the bin release file and the .ino. using bin file it works great the setup wifi ssid shows in an instant. but the .ino method does not.

I can only use the software for a period of time and I need to do the setup once and for all

**Comment by smrtrnx** [comment]
Let me test this out if I won't be disconnected and do the initial setup since we've made changes in the WIFI_CONNECT_TIMEOUT. are you considering the suggestion of having the esp8266 a static ip? 

cheers

**Comment by ivanalayan15** [comment]
im thing it actually, but it should be optional, this is usable also for LAN based actually so im considering it

**Comment by smrtrnx** [comment]
Hmmm its been working lately but i get disconnected from the server, there must be something wrong with my router setup maybe. I don't have a clue right now. I can't connect to the router as of the moment

**Comment by charmedonesfjo** [comment]
I been using the same method (DHCP then mark as STATIC at mikrotik side) of Ivan years ago without NO issue the ONLY different I've been notice is the wifi library... On Ivan's code HE uses <ESP8266WiFiMulti.h> while on mine is Wificlient.h.

**Comment by charmedonesfjo** [comment]
![Shopee_910a4a1e809928122aad8417b5aa1a12.jpg](https://user-images.githubusercontent.com/27848301/133893806-22025872-98dd-42ec-97d6-511f0a5e7b7b.jpg)
Possible include an option for the users to choose a STATIC or DHCP

**Comment by ivanalayan15** [comment]
@charmedonesfjo wow this is nice mock up, i will consider this for the enchacnement

**Comment by bastewifi** [comment]
> ![Shopee_910a4a1e809928122aad8417b5aa1a12.jpg](https://user-images.githubusercontent.com/27848301/133893806-22025872-98dd-42ec-97d6-511f0a5e7b7b.jpg)
> Possible include an option for the users to choose a STATIC or DHCP

nice mas oaky kung may ganito sana :)

**Comment by smrtrnx** [comment]
Should we create a dashboard mock up for every possible functionalities to be added in the future this is a great idea. All necessary MT configuration should be done in single daahboard. What do you think?

**Comment by ivanalayan15** [comment]
@smrtrnx much better to have mock up

**Comment by btambalong** [comment]
> > ![Shopee_910a4a1e809928122aad8417b5aa1a12.jpg](https://user-images.githubusercontent.com/27848301/133893806-22025872-98dd-42ec-97d6-511f0a5e7b7b.jpg)
> > Possible include an option for the users to choose a STATIC or DHCP
> 
> nice mas oaky kung may ganito sana :)

✓✓ nice..

**Comment by ivanalayan15** [comment]
![image](https://user-images.githubusercontent.com/88520539/135375365-40353daa-b2a0-488c-b638-16fd0cfed6a2.png)

**Comment by btambalong** [comment]
bagong version po ba ito boss..

**Comment by ivanalayan15** [comment]
@btambalong yes

**Comment by btambalong** [comment]
thnx po boss..
