### ISSUE TITLE
insert coins not working

### ISSUE THREAD

**Issue by tawingkurimaw** [ivanalayan15/JuanFi#3]
insert coins not working. . .
![235123407_369234498055527_5243510306045200476_n](https://user-images.githubusercontent.com/88753263/128953664-41e47148-31de-42f3-8a56-0fd90198721e.jpg)

**Comment by ivanalayan15** [comment]
temporarily commit the fix for some mikrotik that cannot detect the success login, please pull for the latest ino change, need to manually check first the mikrotik log if login of nodemcu to mikrotik was success

**Comment by tawingkurimaw** [comment]
paano ma pasok ulet admin panel pagkatapos na setup???

**Comment by ivanalayan15** [comment]
http://<nodemcu ip>/admin
