### ISSUE TITLE
Nodemcu Dashboard

### ISSUE THREAD

**Issue by SemiTok2** [ivanalayan15/JuanFi#31]
when you edit system config then nodemcu seems not realy rebooted then LED indication wont light on 2 states blingking and running need to manual power off nodemcu to regain its connection 

Thanks Admin!

**Comment by ivanalayan15** [comment]
hmmmm in my side its working properly, when i edit it its restarting properly actually. may i get a reference video and screenshot of serial logs for it for investigation. thanks

**Comment by ivanalayan15** [comment]
@SemiTok2 is this the lan based?

**Comment by ivanalayan15** [comment]
cannot replicate closing this issue

**Comment by SemiTok2** [comment]
Wireless base sir
