### ISSUE TITLE
Time validity changes

### ISSUE THREAD

**Issue by ivanalayan15** [ivanalayan15/JuanFi#33]
Current logic: When you have for example 5 php is 1 hour and the validity is 1 day, when you extend the time for example 5 php again then validity will become 2 day since it will add up also the validity.

Majority said the logic is correct and we should retain the current logic

But i will also consider other opinions since its also valid, i will add an option in Voucher setting to add optional behavior

**Comment by EdSacis123** [comment]
salamat po

**Comment by ivanalayan15** [comment]
Added new option in system config:

![image](https://user-images.githubusercontent.com/88520539/133959428-c2b89dd8-e52a-4119-b3b0-06f6cd7f3788.png)
