### ISSUE TITLE
Voucher generation option

### ISSUE THREAD

**Issue by ivanalayan15** [ivanalayan15/JuanFi#36]
Voucher generation option:
Username only
Username = password
This is to support mikmon voucher generated codes

**Comment by ivanalayan15** [comment]
html template setting need to turn on

![image](https://user-images.githubusercontent.com/88520539/133959272-35d940eb-90a0-4804-8d78-9b6b9a8c9bc2.png)

**Comment by ivanalayan15** [comment]
System config option

![image](https://user-images.githubusercontent.com/88520539/133959357-7b13d753-7e4e-4235-a46e-a0ac28353d02.png)

**Comment by bastewifi** [comment]
thanks sir
