### ISSUE TITLE
Voucher generation

### ISSUE THREAD

**Issue by ivanalayan15** [ivanalayan15/JuanFi#43]
Voucher code batch generation in admin panel for voucher type selling of voucher codes

**Comment by ivanalayan15** [comment]
added new page in admin

![image](https://user-images.githubusercontent.com/88520539/134850579-6cebbeda-cbec-48c0-a318-2f9dc5e08097.png)


added print preview

![image](https://user-images.githubusercontent.com/88520539/134850642-ae9449b4-6a5b-4fc0-9bb1-b237029bf020.png)

**Comment by bastewifi** [comment]
thanks sir

**Comment by bastewifi** [comment]
hi sir. ask ko lang hindi mabibigatan si node pag madaming code agad ang iggenerate nya? thanks po

**Comment by ivanalayan15** [comment]
@bastewifi medyo mabigat so need to limit it according nlang sayo, i tested arround 20 seems ok p nmn but response time take longer
