### ISSUE TITLE
Voucher code issue/Insert Coin

### ISSUE THREAD

**Issue by Badobads** [ivanalayan15/JuanFi#45]
Found something but not sure if I'm the only one who encountered it. 
Scenario:
Log out and Voucher code will be deleted if you accidentally press Insert Coin Button instead of Login button. 
It would also be good if there's a Remaining Time display while on Pause or in log in page to see if you have still existing time left.

More power and kudos to you sir Ivan.

**Comment by ivanalayan15** [comment]
@Badobads hi, yes this is the existing behavior and its intentional that we are clearing the voucher code field and currently we dont have any way to detect the remaining time of a user if they did not login

**Comment by ivanalayan15** [comment]
closing this issue
