### ISSUE TITLE
parequest :) 

### ISSUE THREAD

**Issue by bastewifi** [ivanalayan15/JuanFi#46]
![Untitled](https://user-images.githubusercontent.com/67478828/134204675-bfeaa3d3-1301-45e7-b3ce-4e20bf900c90.png)
 pede po mag request? :) 

sana po may ganito setup sa admin panel para maassign ung ip at maging static na po..

**Comment by ivanalayan15** [comment]
yep meron n nyang ng raise

https://github.com/ivanalayan15/JuanFi/issues/25

**Comment by ivanalayan15** [comment]
close ko n to para di duplicate
