### ISSUE TITLE
JuanFi wifi portal admin access failed

### ISSUE THREAD

**Issue by wifiuser21** [ivanalayan15/JuanFi#49]
user: admin
pass: admin

incorrect?

**Comment by ivanalayan15** [comment]
its correct, you need to make sure you flash properly the bin file #2

**Comment by wifiuser21** [comment]
ginamit ko boss yun arduino code, andun po b defaul password po nun pra ma edit?

**Comment by wifiuser21** [comment]
by the way ang gamit ko po nodemcu
