### ISSUE TITLE
Datacap limit for voucher rate

### ISSUE THREAD

**Issue by ivanalayan15** [ivanalayan15/JuanFi#50]
Datacap limit for voucher rate

**Comment by ivanalayan15** [comment]
added new field:

![image](https://user-images.githubusercontent.com/88520539/134760358-92c839f5-05cd-43ee-8dfe-6172883ce6a3.png)

Modify portal to add rate

![image](https://user-images.githubusercontent.com/88520539/134760395-7c9753ce-f996-4ac2-b9d1-6b725a63b4f2.png)

add new option core.js to show or enable data rates

![image](https://user-images.githubusercontent.com/88520539/134760410-e3a85f29-c8b3-4eab-919d-e62256018aa4.png)

**Comment by wifiuser21** [comment]
Nice one! its solved, everything!

**Comment by bastewifi** [comment]
thanks sir

**Comment by Justunemoran** [comment]
Data cap limit 2024 plss
