### ISSUE TITLE
Enhancement Idea(s): 10 Minutes Uptime Limit Notification

### ISSUE THREAD

**Issue by smrtrnx** [ivanalayan15/JuanFi#51]
Hello Ivan,

I was thinking about giving the user a notification, 10 minutes prior to their uptime limit. Please consider this enhancement :)

Cheers!

**Comment by ivanalayan15** [comment]
@smrtrnx seems this is a limitation, ideally the user browsing in his own which means he is playing games or doing facebook, so the browser which is the portal is open is not active so we wont able to do notification on it.

**Comment by charmedonesfjo** [comment]
> 
> 
> @smrtrnx seems this is a limitation, ideally the user browsing in his own which means he is playing games or doing facebook, so the browser which is the portal is open is not active so we wont able to do notification on it.

I totally agree.... once the users are validated its hard to triggered such routine / Why ? its already Mikrotik side not nodemcu or login.html file. unless you can create a scheduled routine + SCRIPT that will run every 60secs to get all expiring users code then notify them.

**Comment by ivanalayan15** [comment]
closing this issue @smrtrnx
