### ISSUE TITLE
Generate issue

### ISSUE THREAD

**Issue by bastewifi** [ivanalayan15/JuanFi#56]
hello po sir. pansin ko lang po pag tapos mo mag hulog tapos hindi mo pinundot ung save/connect hindi sya mag aauto generate ng code..

may lalabas na code sa portal pera hindi sya nag ccreate ng code sa Mikrotik..

salamat po

**Comment by ivanalayan15** [comment]
@bastewifi anung version ito

**Comment by bastewifi** [comment]
2.1 po.

**Comment by bastewifi** [comment]
wireless

**Comment by ivanalayan15** [comment]
hmmm oks nmn s version ko

**Comment by ivanalayan15** [comment]
@bastewifi sa extend time b sya or doon sa login n insert coin?

**Comment by bastewifi** [comment]
hmm try nyo po mag insertcoin tapos hulog ka wag mo click ung connect wait mo po matapos ung countdown kung mag cconnect po sayo..

**Comment by bastewifi** [comment]
> @bastewifi sa extend time b sya or doon sa login n insert coin?

sa mismong login po..

**Comment by ivanalayan15** [comment]
@bastewifi yep triny ko sya ngayon oks nmn sya

**Comment by bastewifi** [comment]
2.1 din po gamit nyo?? kasi nag test ako ulit ngaun same padin issue ee.

**Comment by ivanalayan15** [comment]
2.2 gamit ko ngayon pero wala ako changes s logic n yun

**Comment by ivanalayan15** [comment]
@bastewifi anyway baste i will release tonight the v2.2

**Comment by bastewifi** [comment]
thanks sir

**Comment by ivanalayan15** [comment]
this is not happening  on v2.2 closing the issue
