### ISSUE TITLE
request - coin saving when refresh browser during insert coin

### ISSUE THREAD

**Issue by bastewifi** [ivanalayan15/JuanFi#57]
sir sana mag karoon tayo ng SAVE coin.

pag nag hulog ka tapos bigla mo na refresh ung browser o na close. nandun padin sana ung credit na hinulog mo?

thanks sir

**Comment by ivanalayan15** [comment]
@bastewifi hi , i think this is on template logic, let me consider this one

**Comment by bastewifi** [comment]
thanks sir

**Comment by ivanalayan15** [comment]
implemented a work arround together with this issue #68, when you refresh and click the insert coin, it will remain the current active session

**Comment by bastewifi** [comment]
thanks sir
