### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by kuyajnonymous** [ivanalayan15/JuanFi#59]
would it be nice if the pin settings can be configure in the admin panel for the following

LCD PIN
PUSH BUTTON
POWER LED INDICATOR
COIN LED INDICATOR
COIN PULSE
SET PIN (COINSLOT)

screen messages/slide for lcd

This will make the project more universal as it will work on all premade board for esp devices.

**Comment by ivanalayan15** [comment]
@kuyajnonymous its already can be configure in the admin pane, please see the admin panell, only LCD is not because the PIN for LCD is not changable, closing this issue

**Comment by kuyajnonymous** [comment]
hi sir, here is the current premade board that I have. Was planning to test this, however it uses different set of pins.

D1 SDA (lcd)
D2 SCL (lcd)
D7 PUSH BUTTON 
D5 SET PIN (COINSLOT)
D6 COIN PIN (COINSLOT)
D3 INSERT COIN INDICATOR (LED)
D4 POWER INDICATOR (LED)

**Comment by ivanalayan15** [comment]
@kuyajnonymous you can configure it in the admin config
