### ISSUE TITLE
extend time issue

### ISSUE THREAD

**Issue by bastewifi** [ivanalayan15/JuanFi#61]
hi sir report ko lang ung issue sa extend time. pag nag hulog ka tapos hayaan mo lang matapos ung countdown. hindi mag aadd ung time.

pero pag sa LOG IN okay naman  sa extend time lang.

wireless 2.2 gamit.

**Comment by ivanalayan15** [comment]
@bastewifi ok noted on this, it should be portal issue only we need to relogin when user did not click

**Comment by bastewifi** [comment]
thanks sir,,

**Comment by ivanalayan15** [comment]
hi @bastewifi you can now get the fix at master branch, you can just replace directly the core.js
