### ISSUE TITLE
default portal coin-recieved 

### ISSUE THREAD

**Issue by chealski** [ivanalayan15/JuanFi#62]
just experience kania sa lan base using v2.1 walang tunog pag nag hulog ng barya. using captive portal and pisowifi app
pero pag google chrome meron.

before kasi meron lahat sa lumang version v1

**Comment by ivanalayan15** [comment]
@chealski captive portal depends on phone if its supports sound or not, v1 actually does not support any captive portal you need to do login in chrome thats why walang issue before
