### ISSUE TITLE
lan base : voucher user option username + password invalid password error

### ISSUE THREAD

**Issue by chealski** [ivanalayan15/JuanFi#63]
Im using pala lan base default portal 

i try palitan ng voucher user option with username + password pero nag iinvalid login sya
try inbalik sa default na username only and delete yung password sa mt. ayun working.

**Comment by ivanalayan15** [comment]
please change also the loginOption sa core.js wag lang ung sa admin

**Comment by ivanalayan15** [comment]
@chealski

**Comment by ivanalayan15** [comment]
closing this issue

**Comment by chealski** [comment]
copy sir,

need to edit din pala sa core.js may na dagdag pala. tested on mikhmon "username = password" sa setting gumagana sya sa pag create ng voucher via mikhmon.

thank you very much
