### ISSUE TITLE
recconnecting wireless

### ISSUE THREAD

**Issue by bastewifi** [ivanalayan15/JuanFi#67]
sir pansin ko lang. pag pinatay ung AP kung saan naka konek ung ESP8266. hindi na sya mag rereconnecting pag lumabas na ung juanfi setup..

**Comment by ivanalayan15** [comment]
@bastewifi it will try to connect until 45 sec, if not it will go to JuanFI setup, so i made this changes at 

https://github.com/ivanalayan15/JuanFi/issues/66

to do some change in logic and much longer timeout

**Comment by bastewifi** [comment]
thanks sir..

**Comment by ivanalayan15** [comment]
closing this issue to avoid duplicate
