### ISSUE TITLE
cancel button issue

### ISSUE THREAD

**Issue by bastewifi** [ivanalayan15/JuanFi#68]
hi sir. pag nag insertcoin ka tapos cinancel mo. tapos ung second device naman ung gagamit waiting pa sya matapos ung countdown sa insertcoin para makapag insertcoin sya..

**Comment by wifiuser21** [comment]
cancel using push button hehehehe

**Comment by bastewifi** [comment]
working sayo ?? :)

**Comment by wifiuser21** [comment]
yes working nmn

**Comment by bastewifi** [comment]
nice.. sa portal kasi hindi e

**Comment by ivanalayan15** [comment]
@bastewifi yep as of now ung cancel button tlga is parang hide lang sya UI, d bale ggwan ntn ng paraan yn

**Comment by bastewifi** [comment]
thanks sir
