### ISSUE TITLE
wifi hide

### ISSUE THREAD

**Issue by ghost** [ivanalayan15/JuanFi#69]
hi sir, pede bang maka konek ung node kahit naka hide ung WIFI name ng kinokonekan nya??

**Comment by ivanalayan15** [comment]
@bastewifi hi, im not sure actually if its possible can you try it kung makakacoonect?

**Comment by bastewifi** [comment]
hindi sya nakaka konek sir ee..meron kasi ung ibang system na ganitong setup lalu na sa wireless. kasi madalas na pag bitaw ng node.. kaya ginagawa ng iba ni hhide nalang ung SSId para solo lang ung node naka konek

**Comment by charmedonesfjo** [comment]
> hindi sya nakaka konek sir ee..meron kasi ung ibang system na ganitong setup lalu na sa wireless. kasi madalas na pag bitaw ng node.. kaya ginagawa ng iba ni hhide nalang ung SSId para solo lang ung node naka konek

@bastewifi  can you specify the system in particular.... I've tried that approach you've mentioned several times using arduino sketch with ESP8266 but NO LUCK.  Try it your self with very basic sample sketch using wifi example libraries. let me know if its successful.

**Comment by ivanalayan15** [comment]
@bastewifi may i know anung system to

**Comment by ivanalayan15** [comment]
closing this issue since its really working even if ssid is hide
