### ISSUE TITLE
AutoReconnection when disconnected to mikrotik

### ISSUE THREAD

**Issue by ivanalayan15** [ivanalayan15/JuanFi#7]

**Comment by falafox2020** [comment]
Nice update, but the downside is if the telnet recon of the nodemcu reach certain time, dunno the exact number of reconnection, we need to restart the mikrotik for the nodemcu to connect again to the telnet.. 

This problem accur in the other mikrotik system with multi vendo (centralized) setup..

**Comment by falafox2020** [comment]
maybe shift from telnet to api
