### ISSUE TITLE
RATE

### ISSUE THREAD

**Issue by derufu** [ivanalayan15/JuanFi#72]
Unable to set rate for 1 day

**Comment by ivanalayan15** [comment]
@derufu what version you use?

**Comment by derufu** [comment]
2.3

**Comment by ivanalayan15** [comment]
its ok on my side using v2.3 please check your setting

**Comment by derufu** [comment]
I updated its working now! thank you! GoD Bless U!

**Comment by ivanalayan15** [comment]
sure closing this ticket
